### ISSUE TITLE
目录结构

### ISSUE THREAD

**Issue by shirubei** [ShineChen1024/MiaoBi#1]
按照说明，把huggingface的模型文件都下载了放到本地的checkpoints下，执行报错，看了一下代码，发现时应该在checkpoints的miaobi_beta0.9下，追加这一个子目录并把文件挪过去后，
跑python miaobi_generate.py时报错如下：
OSError: checkpoints/miaobi_beta0.9 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/checkpoints/miaobi_beta0.9/main' for available files.

试着把 preprocessor_config.json 从 feature_extrator 挪到 miaobi_beta0.9 下通过

**Comment by ShineChen1024** [comment]
可能是diffusers版本没匹配上。
